name: "CivModern Latest Gradle CI"

on:
  push:
    branches:
      - "master"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Set up JDK 17"
        uses: "actions/setup-java@v3"
        with:
          java-version: 17
          distribution: "corretto"
          cache: "gradle"

      - name: "Patching CivModern"
        run: "./gradlew applyPatches"

      - name: "Compiling CivModern"
        run: "./gradlew build"
        working-directory: project

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            LICENCE
            project/dist/*.jar
