name: "CivModern Release Gradle CI"

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Set up JDK 17"
        uses: "actions/setup-java@v3"
        with:
          java-version: 17
          distribution: "corretto"
          cache: "gradle"

      - name: "Patching CivModern"
        run: "./gradlew applyPatches"

      - name: "Compiling CivModern"
        run: "./gradlew build"
        working-directory: project

      - name: "Publishing CivModern"
        run: |
          gh release upload ${{ github.event.release.tag_name }} "LICENCE" --clobber
          for file in $(find "project/dist/" -maxdepth 1 -type f -name "*.jar"); do
            echo "Uploading $file"
            gh release upload ${{ github.event.release.tag_name }} "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
